# @package _global_
alg: lora_diff
train_text_encoder: true
learning_rate: 2e-5
validation_prompt: "a photo of {} in the Acropolis"
lora:
  use_lora: true
  lora_r: 16
  lora_alpha: 8
  lora_dropout: 0.0
  lora_bias: "none"
  lora_text_encoder_r: 16
  lora_text_encoder_alpha: 8
  lora_text_encoder_bias: "none"
  lora_text_encoder_dropout: 0.0
  UNET_TARGET_MODULES:
    - to_q
    - to_v
    - query
    - value

  TEXT_ENCODER_TARGET_MODULES:
    - q_proj
    - v_proj